FROM almir/webhook:2.8.3

USER root

ENV HOME=/home/webhook

RUN apk add --no-cache docker-cli docker-cli-compose git openssh-client

COPY docker/webhook-entrypoint.sh /usr/local/bin/webhook-entrypoint.sh

RUN chmod +x /usr/local/bin/webhook-entrypoint.sh

USER 1000:1000

ENTRYPOINT ["/usr/local/bin/webhook-entrypoint.sh"]
